CREATE PROCEDURE Create_Images_Comments

AS

CREATE TABLE Images
(
imageID INTEGER NOT NULL,
path VARCHAR(20) NOT NULL,
commentID INTEGER,
)

ALTER TABLE Images
ADD CONSTRAINT PK_Images PRIMARY KEY (imageID)

ALTER TABLE Images
ADD CONSTRAINT FK_Images FOREIGN KEY (commentID) REFERENCES Comments(commentID)


CREATE TABLE Comments
(
CommentID INTEGER NOT NULL,
dateAndTime DATETIME NOT NULL,
comment VARCHAR(200) NOT NULL,
imageID INTEGER,
)
ALTER TABLE Comments
ADD CONSTRAINT PK_Comments PRIMARY KEY (commentID)

ALTER TABLE Comments
ADD CONSTRAINT FK_Comments FOREIGN KEY (imageID) REFERENCES Images(imageID)
